### ISSUE TITLE
Metric for evaluation and other issues

### ISSUE THREAD

**Issue by rabowskyb** [awslabs/fraud-detection-using-machine-learning#1]
I found the following issues when running this notebook:

1)  Metric for evaluation:  after running this notebook, I found that the recall was only about 73%, which for a fraud detection use case should be targeted at a higher level such as 90%.  

     Suggested resolution:  follow the example at https://github.com/awslabs/amazon-sagemaker-examples/blob/master/scientific_details_of_algorithms/linear_learner_class_weights_loss_functions/linear_learner_class_weights_loss_functions.ipynb, including:

        Set 'binary_classifier_model_selection_criteria': 'precision_at_target_recall'
        Split the dataset into validation and test along with train.
        Use class weights etc.

2)  The data upload cell cannot be run as written.  Instead, use the default session bucket or allow the user to provide their own:

          bucket = session.default_bucket()
          prefix = 'fraud-detection-end-to-end-demo/linear-learner'

**Comment by sojiadeshina** [comment]
Hi @rabowskyb , Thanks for the suggestions. 

For 1, one of the targeted improvements is to improve the recall, and adding class weights is one of the ways we're looking to do that, in addition to more data preprocessing and other techniques.

For 2, the ipython notebook is meant to be used in concert with an aws cloudformation template that builds the resources like the s3 bucket. If you're not deploying the cloud formation template, then you will have issues like the one you describe. However, like you found out. You can easily change the bucket name variable to point to the bucket you want.

**Comment by rabowskyb** [comment]
Great, thanks, I will stand by for the updated version.  Is there a timeline so we can make sure that users get the benefits of the improvements?

**Comment by vishaalkapoor** [comment]
(edit) Apologies for the delay, due to scheduling I have to update the target to Nov 15. I will do a deep dive by Nov 1st and report back.

**Comment by vishaalkapoor** [comment]
Code is being deployed with latest improvements including XGBoost and sampling. Assigning to @thvasilo. We'll update the Git repo with the latest code and there will be an official launch in the coming weeks.

**Comment by thvasilo** [comment]
Hello @rabowskyb the latest update should fix this issue, feel free to re-open if this still persists, and open new issues with any new problems that come up. Thanks!

**Comment by vishaalkapoor** [comment]
Hey @rabowskyb  - please find the release notes below for the latest release (2.0) of this solution:

**Added**

- unsupervised learning model with Amazon SageMaker Random Cut Forest
- data upsampling techniques like SMOTE for addressing imbalanced data
- More interpretation of results
- supervised learning model with XGBoost
- Amazon API Gateway entrypoint


**Removed**

- Supervised learning model with SageMaker linear learner

https://github.com/awslabs/fraud-detection-using-machine-learning/blob/master/CHANGELOG.md 

Cheers,
Vishaal
