### ISSUE TITLE
Broken citation link

### ISSUE THREAD

**Issue by ehsanmok** [awslabs/fraud-detection-using-machine-learning#4]
In notebook, the cited link [http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.68.6858&rep=rep1&type=pdfor](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.68.6858&rep=rep1&type=pdfor) is broken.

**Comment by thvasilo** [comment]
That has been fixed in the latest version.
