### ISSUE TITLE
Stack fails to deploy on us-east-1

### ISSUE THREAD

**Issue by mrichman** [awslabs/fraud-detection-using-machine-learning#5]
`SolutionAssistantStack` resource is HTTP 403 on https://s3.us-west-2.amazonaws.com/sagemaker-solutions-build-us-west-2/Fraud-detection-using-machine-learning/build/ecea829bfbfd1c53fd6a004f9537412c.template

**Comment by thvasilo** [comment]
Hello @mrichman, thank you for pointing this out, I fixed the issue and tested deploying to all available regions. Feel free to re-open if you run into any issues.
